# Generated by Django 4.0 on 2021-12-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
    ]
