# Generated by Django 3.2.9 on 2021-12-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blogpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.CharField(default='2021-12-18 00:30:45.617418', max_length=50),
        ),
    ]
